import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { DateRangeProvider } from "@/components/contexts/DateRangeContext"; // ✅ CORRIGIDO

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Connectados_shadcn_001",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en" className="dark" suppressHydrationWarning>
        <body
          className={`
            ${geistSans.variable} ${geistMono.variable} antialiased flex 
            bg-white text-slate-900 
            dark:bg-linear-to-b dark:from-neutral-900 dark:to-neutral-700 
            shadow-lg shadow-black/90 dark:text-slate-50
            bg-no-repeat bg-cover 
          `}
        >
          <main className="w-full h-screen flex flex-col">
            <div className="p-4 grow overflow-y-auto">
              {/* ✅ Provider envolve todo o conteúdo */}
              <DateRangeProvider>
                {children}
              </DateRangeProvider>
              <Toaster position="top-center" richColors closeButton />
            </div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}